=== victorananth/BRS-Document-Schema-Design/BRS Document Schema Design/BRS-Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="title" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="contributors" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="contributor" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType >
                                                <xs:sequence>
                                                    <xs:element name="name" minOccurs="1" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                                <xs:attribute name="role" use="required">
                                                    <xs:simpleType >
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="creator"/>
                                                            <xs:enumeration value="contributor"/>
                                                            <xs:enumeration value="illustrator"/>
                                                            <xs:enumeration value="editor"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="language" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="series" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="contents" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="subjects" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subject" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="lang" type="xs:string" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="publisher" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="place" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="date" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="identifiers" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="identifier" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="type" use="optional">
                                                            <xs:simpleType >
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="lc"/>
                                                                    <xs:enumeration value="isbn"/>
                                                                    <xs:enumeration value="oclc"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="format" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="availability" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="location" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Grainger Engineering Library"/>
                                                                <xs:enumeration value="Main Library"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="callNumber" minOccurs="1" maxOccurs="1"/>
                                                    <xs:element name="available" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== victorananth/BRS-Document-Schema-Design/BRS Document Schema Design/BRS-Document 1.xml
<?xml version="1.0" encoding="UTF-8"?>

<catalog
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://cs598.org/ns BRS-Schema.xsd">

    <book
            id="alma99444534012205899"
            url="https://i-share-uiu.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma99444534012205899&amp;context=L&amp;vid=01CARLI_UIU:CARLI_UIU">
        <title>XML Schema Essentials</title>
        <contributors>
            <contributor role="creator">
                <name>Wyke, R. Allen</name>
            </contributor>
            <contributor role="contributor">
                <name>Watt, Andrew</name>
            </contributor>
        </contributors>
        <language>English</language>
        <series>Wiley XML essentials</series>
        <subjects>
            <subject lang="fr">XML (Langage de balisage)</subject>
            <subject lang="fr">Bases de donn√©es -- Gestion</subject>
            <subject lang="en">Database management</subject>
            <subject lang="en">XML (Document markup language)</subject>
            <subject lang="en">XML</subject>
        </subjects>
        <publisher>
            <name>Wiley</name>
            <place>New York</place>
            <date>c2022</date>
        </publisher>
        <identifiers>
            <identifier type="lc">2002001951</identifier>
            <identifier type="isbn">0471412597</identifier>
            <identifier type="isbn">9780471412595</identifier>
            <identifier type="oclc">(OCoLC)48957890</identifier>
            <identifier type="oclc">(OCoLC)ocm48957890</identifier>
        </identifiers>
        <format>xiv, 386 pages ; 24 cm</format>
        <availability>
            <location>
                <name>Grainger Engineering Library</name>
                <callNumber>005.72 W975x</callNumber>
                <available>false</available>
            </location>
        </availability>
        <contents>
            Part One: Getting started
            -- Elementary XML schema
            -- XSD elements
            -- Adding attributes
            Part Two: Going beyond DTDs
            -- Applying datatypes
            -- Data facets
            -- More about data facets
            -- Grouping elements and attributes
            -- Deriving types
            Part Three: Next steps
            -- Uniqueness and keys in XSD schema
            -- Bringing the part together
            Part Four: Appendixes.
        </contents>
    </book>
</catalog>
